### ISSUE TITLE
Add community partner logos

### ISSUE THREAD

**Issue by frnzmlc** [GitNation/ReactDay.Berlin#11]
images: https://drive.google.com/drive/folders/1UdXMzZuy-u7T0ltZhHBJxZyZdq6h4RBx?usp=sharing

links:
https://www.meetup.com/framsia/
https://graphql-finland.fi
https://www.meetup.com/madridjs/
http://ng-girls.org
https://warsawjs.com
https://www.meetup.com/ReactJS-Girls-London/
https://lesbianswhotech.org/about/
Travis Foundation -> https://diversitytickets.org
https://www.dotconferences.com

**Comment by operatino** [comment]
done

**Comment by frnzmlc** [comment]
Add one new logo
https://drive.google.com/open?id=1QP-LyYix79VWdbs9d0_uJsJwOGhBXhWt
link to: https://www.meetup.com/React-Native-Bangalore-Meetup/
